#!/usr/bin/env bash
#
# Script to monitor PowerDNS performance
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#%# family=auto
#%# capabilities=autoconf

readonly PDNS_CONTROL=$(type -P pdns_control)
readonly SED=$(type -P sed)
readonly AWK=$(type -P awk)

readonly COMMAND="${PDNS_CONTROL} show"
readonly STATE_FILE="/var/lib/munin/plugin-state/pdns_rel.state"

if [[ "$1" == "autoconf" ]]; then
        echo yes
        exit 0
fi

if [[ "$1" == "config" ]]; then
        echo 'graph_title Power DNS Packet Cache Performance'
        echo 'graph_args -l 0 --upper-limit 100 --base 1000'
        echo 'graph_vlabel %'
        echo 'graph_category Power DNS'
        echo 'graph_info This graph shows the Power DNS packet cache performance on the machine.'
        echo 'packetcache_hitrate.label packet cache hitrate'
        echo 'packetcache_hitrate.type GAUGE'
        echo 'packetcache_hitrate.min 0'
        echo 'packetcache_hitrate.max 100'
        echo 'packetcache_hitrate.info Hits on the packets cache'
        exit 0
fi

HITS=$(${COMMAND} packetcache-hit)
QUERIES=$(${COMMAND} udp-queries)
OLD_HITS=$(${SED} -n '1p' "${STATE_FILE}")
OLD_QUERIES=$(${SED} -n '2p' "${STATE_FILE}")

if [ -f "$STATE_FILE" ] &&
   [ $(ls -l --time-style=+%s "$STATE_FILE" | ${AWK} '{print $6}') -gt $(date --date="7 minutes ago" +%s) ] ; then
	d_hits=$((${HITS} - ${OLD_HITS}))
	d_queries=$((${QUERIES} - ${OLD_QUERIES}))
	if [ $d_queries -gt 0 ] ; then
	   echo "packetcache_hitrate.value $(( $d_hits * 100 / $d_queries ))"
	fi
fi

echo $HITS > $STATE_FILE
echo $QUERIES >> $STATE_FILE
